# Enable C++ support
language: cpp
# Compiler selection
compiler:
    - clang
    - gcc
addons:
    apt:
        sources: ['kalakris-cmake']
        packages: ['cmake']
# Build steps
script:
    - mkdir _build
    - cd _build
    - cmake .. && make
